{
 "title": "Temperatures Rue Romain",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Building Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "  from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"tempC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"device\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"device\"])"
    }
   ]
  },
  {
   "title": "Sensor Events",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_events\")\r\n  |> filter(fn: (r) => r._field == \"message\")\r\n  |> map(fn: (r) => ({\r\n      timestamp: r._time,\r\n      device_name: r.device,\r\n      event: r.event_type,\r\n      details: r._value\r\n  }))\r\n  |> sort(columns: [\"timestamp\"], desc: true)",
     "rawSql": "from(bucket: \"sensor_data\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r._measurement == \"device_events\")\r\n  |> filter(fn: (r) => r._field == \"message\")"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 14, "w": 9, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sensor_data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_events\")\r\n  |> filter(fn: (r) => r.severity == \"error\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group(columns: [\"device\"])\r\n  |> sum()"
    }
   ]
  }
 ]
}